### ISSUE TITLE
Changelog/Readme Updates

### ISSUE THREAD

**Issue by stackpoint** [TheDivexz/excelmakesbelhappypack#59] opened 2020-05-06 08:41 UTC
To update the documentation and make a new release version:

- settle on a version number and release name if any
- edit `README.md` with a breakdown of most important new version features, version number and release name
- edit `changelog.txt` with all the changes
- git commit
- wait for the bot to update the startup event
- git pull
- make a new version tag in git
- git commit --tags

Automation:
After `README.md` is edited and committed, a bot will update the changelog event you get at gamestart with the top content.
After a tag is committed, a bot will create a new zipped release on GitHub

**Comment by Grociu** [comment] 2020-05-07 14:54
This should be helpful, these commits edit the mod code (as opposed to python/GitHub scripts) since 26th April.

**10th May 2020***
Every 250 developement gives a leader up from 100

aa9d3b3c493c0f68c16fa51aeead79f63bf13c65
Pass a Law now restricted to tags without the finalgov reform

d30adb3ffb13e632773bebff845834624ff0c6f2
For republics add scaling reelection costs based on months of ruling.

4f93af4d65a5e74addeace49d6dd908809b04cf9
Number tweaks to AI bonuses in hard mode:
land_morale = 0.04 down from 0.075
discipline = 0.02 down from 0.035
manpower_recovery_speed = 0.1 up from 0
naval_morale = 0.04  down from 0.1
ship_durability = 0.02 up from 0
global_sailors = 500 down from 1000
sailors_recovery_speed = 0.1 up from 0
heavy_ship_power = 0 down from 0.075
galley_power = 0 down from 0.075 
light_ship_power = 0 down from 0.075
transport_power =0 down from 0.075
build_cost = -0.1 nerfed from -0.15
monarch_admin_power = 0 down from 1
state_maintenance_modifier = -0.1 buffed from 0

2259006dc6c7cdfbf779521fbefad4ccbcdc147e
Every 100 developement gives a leader slot due to a popular demand fo more leader slots

c7bd00f89f3cecd8cb748aacc3ffdd59bbdb099a
AI now more likely to take a hit to stability to preserve being a Republic


**9th May 2020**
AI now more careful before spending legitimacy_equivalent on Estate clicks (spewing Rep Tradition was bad)

cb43e7a3b7618d7ca1fb21432b85a5af5754ba0a
NDefines.NGovernment.GOVERNMENT_REFORM_YEARLY_BASE_PROGRESS = 8.0 (down from default 10) 
modifiers that impact global autonomy based on number_of_provinces removed pending redesign od system


b8b9ebac12e3da7eb07d1154fea9a22bde2037d0
Tweak AI Fort building conditions: Will need to have no loans monthly income of 10 (up from 5) or income of 5 (up from 3) and 200 in bank.

8380526515b4e0208ec4bd0f69d3850cc3531c4d
Resetting AI values for Orthodox Icons - more logic




Basic rework of the Adivasi estate.
Estate interactions numbers and AI condition tuning
Estate Interactions are now color coded by impact of click on loyalty and influence of current Estate
Estate Interactions for 3 main ones are now reordered to look pretty and logical.

**8th May 2020**
939d4365b620855f9570e21ad2fd7288cc9b4537
Multiple minor bug fixes in Missions (cleanup of triggers, effects and whitespace)

AI will now do Clergy, Noble and Bughers Estate clicks
Clergy, Nobility, Burghers clicks normalized
Missing interactions from IV added to the three main Estates
Recruit from Domain and Ask for Reform Support are now both at -10 loyalty +10 Influence
Impose a tax now scales with held land, not Influence

**7th May 2020**
68e257dc2d5570eb25851de16236ec23a982c9ca
Beginning of the cleanup of Estates

48c1c4adce570e0e040689d0c45a966dea6e8a7e
Add a "Back' button to the Institutions view in the technology tab


b322a3c3ebb09a6429ce7bd1d69d470292ef234a
Added tooltips to governmet buildings to explain how the Empowered Edicts work

1ef740b42a71f37b3ea66f0cf79300a49c4e7833 d750671306bba24db954faf1d10472a1bd295da0
Docks lineup of buildings now availible without idea investement.
Add scaling for Galley Ideas Navy Forcelimit modifier instead of flat

5fb014e13151f0c23c5a75fad5f02cff53c22b58
AI will now try to ennact war taxes(?)
AI troop assingment logic tweaks:
NDefines.NAI.ARMY_DISTANCE_SCORE_IMPACT	= 1.25 from default 0.5
NDefines.NAI.BORDER_DISTANCE_SCORE_IMPACT = 10 from default 3.0
NDefines.NAI.REGION_PLANNING_HOMELAND_PRIORIZATION = 25 from default 3.5
NDefines.NAI.MIN_FORCE_LIMIT_SHARE_REGION_ASSIGN = 0.2 from default 0.1
NDefines.NAI.ACCEPTABLE_BALANCE_DEFAULT = 1.5 from default 1.75
NDefines.NAI.ACCEPTABLE_BALANCE_FRIEND_IN_COMBAT = 0.85 from default 0.75


ba7ce8383c6491cccd806fb0bda16b8b09861077 0ef2bf5636610ee5d3d2fe195542643d000a3130
AI will now do Church Estate clicks


**6th May 2020**
7767a6e7b76368547a2a3a4621409e3cb7c2fa96
Update AIMercHelper.txt
Add conditional so AI can rebuild army faster after huge army loss/stackwipe.
(Activates MercHelperAI when at half force limit)

9d56fbe060a22340a31b616f6594208833733b21
Decision checks buffer
Add treasury and monarch point buffer to ai_will_do so the AI won't exclusively save/spend for the decision.

725e004a2436d8cc9b46b65a116edd256053c01c
Excelmakesbekhappypack has been spellchecked, and is now an en-US mod with love for the letter 'z' and neighbors

**5th May 2020**
e984b00c1dd891fb8c0d2e89f483246d53d3ed0b
Disable development cost-province cost triggered modifier and AI idea cost reduction.

b15b55b76980a5e4b838a5f51e10847391dbecee
Corrections to the Dynastic Idea group.

cbcb9d97c73022036a714f82c2d39dfc964b0d6e cefbd62c98119d7217af91aed2b7ae6eb3acf7fd
Implement a decision to upgrade your Center of Trade meant for AI.
If multiple candidates, will upgrade CoT in the province with most provincial trade power.
Button deemed convenient, tooltips for the player added.


**4th May 2020**
023fb518d0a0109256262469c1d08a0fb0b3c4cc
Add flavor text for vanilla ideas that had their function changed

51cc56eb911aa60ed356df01049efd562049b308
AI Tweaks:
NDefines.NAI.DIPLOMATIC_ACTION_GUARANTEE_POWERBALANCE_FACTOR = 25 from default 80
NDefines.NAI.MIN_INCOME_FOR_SUBSIDIES =	50 from default 20
NDefines.NAI.CALL_IN_ALLIES_POWER_RATIO = 2.5 from default 4.0
NDefines.NAI.ADVISOR_BUDGET_FRACTION = 0.3 was 0.10, back to default
NDefines.NAI.ARMY_BUDGET_FRACTION = 0.7 was 0.6, back to default
NDefines.NAI.NAVY_BUDGET_FRACTION = 0.5 was 0.4, back to default
NDefines.NAI.FORT_BUDGET_FRACTION = 0.45 was 0.5
NDefines.NAI.MISSIONARY_MAINTENANCE_SHARE = 0.3	from default 0.2
NDefines.NAI.MIN_SHIPS_FOR_ADMIRAL = 20	from default 10
NDefines.NAI.BIGSHIP_FRACTION = 0.35 from 0.3
NDefines.NAI.TRANSPORT_FRACTION = 0.3 from default 0.5
NDefines.NAI.ARTILLERY_FRACTION = 0.30 from default 0.35
NDefines.NAI.FORCE_COMPOSITION_CHANGE_TECH_LEVEL = 16 from default 11
Add interesting testing options at end of file

8ec45e58495184becaba8c646fd7d7cde35d4296
General bugfixes:
Last of the trivial bugfixes out of the error.log file

5a05d5bb15b1b0fc5cd00ea984ccdc31a66260b5
Loosen AI merc restriction
Triggered modifier not allowing merc idea AI to buy mercs at +X% manpower.
manpower_percentage = 0.25 was 0.20

4dfccd0c31296caa0a4526110cff03137dfc3489
Remove extra dev cap options
Made it so you don't have to scroll down the options bar to read the MP option.

55a8599d6321e4a58c112d7d36f47689a38e6074
Update 01_cb_Idea_Variation.txt:
Prevent Dynastic Wars on subjects

**3rd May 2020**
291eecd1bd8589dbb9ad7190b4134c951b442b81
Multiple minor bug fixes;
Adds a highlight for the 'use ME missions' decision;

05a2793205a1394cca1560017e0fe50d74b7c9f1
Update ME_Maya_Missions.txt:
Using any_province in provinces_to_highlight scope causing severe lag;

**2nd May 2020 2.5.3**
1c91e4c8d85a5b7f644cafc1b7ff739acba26a04
Dev Click Defines:
Can manually disable vanilla development defines if use dev-click function. Can't dynamically change it though;

6abd6db16eaebac364461b7f15999c9327d904aa 7bb21adecaacc5b463ac7bf5a1131283d231e467
Various minor bugfixes

4f3aeeb0a2d16be445cad947cdfa235d3884a23e
local_build_cost modifier to build in province reduced to 0.005 per dev (was 0.01) 
`d94a45f1ede3b6c3da9558e5467662e6b6843c73`
local_build_cost modifiers globally reduced

**1st May 2020**
dd13b489b626f982cd6d38d185edefdfc4379377
Elective monarchies now will get the +1 skill bonus from ideas;

3a962291804f68c8f5761d417bc8cf890bddaf3c
AI with positive personality now more likely to avoid debasing currency
Adds Emperor of China Personalities: Petty and Humane

189831e951665168d81ceef080b4dec1d9d8f406
Adjust vanilla religious idea events:
Use scripted trigger to check for all religious idea groups instead of the default vanilla one;

271331e40006bbe2321548cc4b0da6e599414a25
Update CastillianDecisions.txt:
Added logic so AI Castile doesn't pay for bureau forever and while poor;

e0a973a37c0a18d8a196bfa82a1ef35acaee4035
Creates a Dev click startup event
Allows to set cap or disable switch needed for **MP** sessions because of **DESYNC** **ISSUES**.
 
8001fd2f129e0298d87665da166bc70ac809c54f
Lower development penalties on build cost:
local_build_cost from 0.03 to 0.02;

20b7ea4d1211a7eee6347eda5b55dfd56607a789
Mission buildings fix
Prevents missions from adding buildings you cannot build and removes all depreciated buildings correctly before adding free buildings.

f8beef78ce1e40fe4c0e332e8c7bf21e4c4069f2 f0f306df807cbf59ef30ea23eba9aab116517b92
Adjustments for events and missions rewarding incorrect amount of religious points

**30th April 2020 v0.2.5.2**

d10edcc4fee7fa62abc467a37de76df079857dc4
Fix for a Linux loading bug

84d54c3691ce240f002b2f0bd3dc878bdd99b4bf
Add a new look for the mission interface

9b1c1e081e8e2741e3c150963e21c27c0bcf94fc
Fix building references using scripted triggers and effects

a8fba81eca578f1cdb7c7227178d9b2cb56cf712
Scripted triggers and effects for modpack buildings;

a4767b98ae1f5eeaa6ed94bf03443d3929bd0c27
Fix ME decisions to build buildings;

dbcef208bdbb06bbadd7bd9fd5af11a82789b1cc
Add Vanilla events with add_building effects;

**29th April 2020**
c8786605e7a2492462fbfbc6dc25b98fb468fa35
Update Idea Variation Settings.txt Wait a month before asking the players again;

4faec4ca575e25dad33e8050aeacd1c9cec0856e
GitHub action to zip the mod pack;

5915e1835aea6da50d6f282ddb4bdd09a0136f06
Implement Experimental AI build order; INFO: https://github.com/TheDivexz/excelmakesbelhappypack/issues/20

fb30159a872fb000deb5ad11de76710d7bb3c57a
Underline Privileges estate interaction is now always = yes for most estates;

115685c8be63e524fbc582789a55e83fa377d2a4
NDefines.NGame.MAX_CUSTOM_COUNTRIES = 50 added;

9078ee0ce3e7e2e2651763c33006908dfebba576
Country tags updated: removed Brtish Trade Company tags, added EastJianzhou, Formosa, Nivkh, NorthHaixi, Solon;

**28th April 2020**
6f1281d9d50a89099943c6487041df955098f2fa
AI less likely to only dev push Gold;

ca5ead3cb75a57d653ff2cb3bb2f27a700d10818
Added flat development costs along with scaling development costs.
developement_scealed local_developement_cost is now 0.2 up from 0.015
provincial production, manpawer and tax increased by local_development_cost = 0.01

3246663c2650479f93e59de665518764b199646c
"...vanilla code does not recognize references to building entries that are made AFTER the calling building. In this situation the town hall building would not be recognized because it's declared after courthouse.";

e9a029db466ba40a35c9f7a1f3c08c7f4ddf3c7e
Changed religious_ideas references to full_all_reli_idea_groups and has_all_reli_idea_groups for all the custom religious idea groups;

6c55ff90bf66c17de99323f8456e76ae5b491050
Dev click cap to 900;
AI will not save more than 900 points scaled to their current point cap. Development taken will be recorded in the decision tracker;

**27th April 2020**
e2f2a2d7451f6a4646dda3098769ae37e753226d
Fix requirement for Provence mission

d9346da33e0e49a7442a4c63869a5d87ab4e037e
Clean-up for initial event code

06a97904fa233a9fae36f21c7cc9484926bb5c8e
Improved text for disinheriting heirs

5083f6fe2661be342ca6b9d5a2f34685845fb3f3
Added fancy loading screens

53e420dfa15b024769672263bd3fc5eea514d100
Mission interface overhaul

2e3e4947a9b144fba5d539803d5ecdc776087861
Corrected trigger for Paid Court to the Burghers interaction.

40ad52414800e19433548cbdff7d4568dc1156ae
Advisor types now have the monarch point icon.

84b29f2b85d9af94f31432667395f9e8de85bf92
Dropbox Changes:
local_development_cost scaled modifier added back at 0.015
local_development_cost scaled modifier removed
tested it at 0.01 and 0.02, overall felt too strong
overall this is still a buff to development costs, which will be factored into other changes

**26th April 2020**

c82f6ccab9ba52bdd6e0341b5b618a507dc0a9cb and forward
Create DropBoxCron.yml - Dropbox download GitHub action and multiple iterations upon it

b3114c01571ceb81957f8ed2b37eb94815a770ea
Creates the changelog;
Clean up of starting bookmarks;
Clean up of historical_idea_groups and references to old idea_groups;
Clean up in common/defines;
Clean up in common/static_modifiers;
Clean up in common/triggered_modifiers;
Non-standard estates changed to fit the standard estates scheme - local_autonomy changes and modifiers, and no floor;
Dhimmi provinces no longer can be converted when neutral attitude;
Nationalist estate "Officer Positions", "Demand Support" now on 20 years timer (was 15);
Exploration Ideas - AI logic for picking this adjusted;
Create interface/modifier_interface.gui;
Remove the word "Ideas" from Idea names, to clean up what policies you unlock;
Power Projection is now PP Size;

**Comment by Grociu** [comment] 2020-05-09 18:48
Before I start updating documentation here, let's discuss what should be the structure here? How do we envision the documentation in the modpack?

Existing documentation elements:
- GitHub `README.md`
- the `changelog.txt` file
- in-game statup changelog

Am I missing any? I know some automation exists here, if you could explain the current scheme that would be helpful.

**Comment by stackpoint** [comment] 2020-05-09 20:13
So the automation involves:

1. Update the [readme](https://github.com/TheDivexz/excelmakesbelhappypack/blob/master/README.md)
2. Adding a [tag](https://stackoverflow.com/questions/18216991/create-a-tag-in-a-github-repository)
3. [Github actions bot](https://github.com/features/actions) will see the new tag and generate the [startup event](https://github.com/TheDivexz/excelmakesbelhappypack/commit/cf2c35ad4c223b365e6e29f8c3d5c515d0b7802d) using the readme
4. It will then generate a [release](https://github.com/TheDivexz/excelmakesbelhappypack/releases)

**Comment by Grociu** [comment] 2020-05-09 20:18
Is this all in one script? What triggers this script? Where does the script take the data to update README.md from?

**Comment by stackpoint** [comment] 2020-05-09 20:20
I miswrote, humans do 1 and 2 and the bot does 3 and 4. Adding the tag triggers the bot.

**Comment by Grociu** [comment] 2020-05-09 20:27
OK. I understand this workflow now. 
I'm going to edit the README.md with the important stuff and changelog.txt with a more detailed breakdown. We're due for a release anyway.

**Comment by Grociu** [comment] 2020-05-10 09:39
The docs are up to date as of 10.05.2020 release v2.6 4efc557f22c20b708a2b856da9becd7c1f68d081

**Comment by Grociu** [comment] 2020-05-12 11:04
May 14th 2020
Added missing localization for Timurid Princes Events
Fixed pathing for new trade connections to be more visually pleasing
You can now properly save Army Templates
Fixed a bug where trade from Caribbean was passing through Mars in an attempt to establish Elon's Colony.
Added historical trade node connections in the Americas:
- st_lawrence to chesapeake
- james_bay to north_sea
- chesapeake to carribean_trade
- brazil to carribean_trade
- patagonia to lima
- carribean_trade to english_channel
Full map: https://github.com/TheDivexz/excelmakesbelhappypack/pull/77#pullrequestreview-411440345


May 13th 2020
Missions will now understand that higher tier mod buildings exist.
AI now will take up to 5 loans loans to pay for recruitment of regular troops if needed.
You now must actually have the relevant ideas to own idea buildings
Triggers province_has_at_least_num_of_buildings, province_has_building_of_group now account for new buildings
AI will do Maratha and Vaishyas Interactions, file cleanup 

May 12th 2020
Estate Interactions gained from Ideas now give just a flat 10 loyalty at no cost. 
AI now with new fort placement logic
Flavor text for modified Ideas changed Fleet Base Ideas, Assimilation, Conscription, Monarchy, Theological, Republican, Expansion. now with 90% more alliteration
Repulbican Ideas no longer give 20 max absolutism, gain diplomat instead, Idea 5 swapped with 7
Imported some vanilla event files and merged mod's event changes into those.
Fix event errors caused by duplicate event numbers in same namespace (39 id treated the same as 39b)
Fix crash in Austrian Germanization Events
Estate Interactions will no longer be available while a different estate's disaster is happening
Clean up in Institution spawn year variable assignment
Localization fix for same color CB
AI will now do Nationalists, Jains, Rajput, Brahmins clicks, cleanup in files, AI logic improved

May 11th 2020
Impose a Tax will now show a tooltip to reflect recent scaling change (scales with dev)
AI will evaluate which Anglican aspect to click better.
Clean up on decisions available to the player at game start
Clarifications on the decisions to explain Empowered Reforms
Decision to Reform Monarchy is now disabled at startup - you can do it in Gov Reforms.
AI's Mellister Dev Click decision is now hidden from players
Corrected the text for Government Reform switching - no longer requires a stab hit.
Changed the Tooltips in the decisions for Natural Development to be more explanatory 
AI will now do Cossack, Dhimmi, Janissary interactions, cleanup in those files

May 10th 2020
Change the startup popups to be more user friendly - added explanation in tooltips, remove references to unused settings
Edit the changelog script to not refer to current version (bot can't keep up with GitHub tags)
Fix scrollbar on the macrobuilder

**Comment by Grociu** [comment] 2020-05-15 11:43
The docs are up to date as of 15.05.2020 release v2.7.1 421c9f9e3960599bebf7a6b9673827fa08f2c1dd

**Comment by Grociu** [comment] 2020-05-18 06:46
May 17th 2020 current as of cbd22d5bc68fe53b30ab1aeaa74e653f134f8891
A lot of small fixes cleaning the startup log.
Missing localizations for 'Get my ideas' evnets.

May 16th 2020
IV Hard Mode AI Bonuses now properly scale with Future Ages:
Rough estimate as compared to Age of Discovery: Age of Reformation: 2x Age of Absolutism: 3x Age of Revolutions 4x
Free policies for AI are now +0/+1/+2/+3
GBR can now form Angevin Empire
Further adjustments to American Trade:
Trade areas renamed. provinces reassigned to proper nodes, trade map improvements
Rio Grande, Cuiaba removed.
Chile and Potosi added.
Grand Lakes now a starting node.
Great Lakes ---> Mississipi
Further details:
https://github.com/TheDivexz/excelmakesbelhappypack/commit/4fd993cea2d0a5f2c967cc5b4bd4746219f0ca50
Fix for Estate disaster firing at 80 influence instead of 100
'Sack of X' event no longer triggers when unsieging your own, your subjects, or your overlords fort. Developement threshhold for this event lowered to 10 (from 15) but you can now only get this if you're below 20% professionalism (from 50%). 


May 15th 2020
AI bonuses changes in hard mode:
global_manpower = 0 (down from 5.0)
global_manpower_modifier = 0.04 (up from 0)
manpower_recovery_speed = 0.04 (down from 0.1)
land_forcelimit_modifier = 0.04 (down from 0.1)
global_sailors = 0 (down from 500)
global_sailors_modifier = 0.04 (up from 0)
sailors_recovery_speed = 0.04 (down from 0.1)
naval_forcelimit_modifier = 0.04 (down from 0.1)
global_tax_modifier = 0.04 (down from 0.1)
production_efficiency = 0.04 (down from 0.1)
trade_efficiency = 0.04 (up from 0)
advisor_cost = -0.04 (down from 0)
state_maintenance_modifier = -0.04 (up from -0.1)
interest = -0.2 (down from 0)
build_cost = 0 (up from -0.1)
fort_maintenance_modifier = -0.04 (down from 0)
missionary_maintenance_cost = -0.04  (down from 0)
land_maintenance_modifier = -0.04  (down from 0)
merc_maintenance_modifier = -0.04  (down from 0)
reinforce_cost_modifier = -0.04  (down from 0)
naval_maintenance_modifier = -0.04  (down from 0)


Further changes to the American trade network:
Philippines -> Caribbean connection added
Panama, Amazonas trade nodes are no longer a thing
Areas and Provinces reassigned to proper trade nodes
Detailed changelog for this:
https://github.com/TheDivexz/excelmakesbelhappypack/commit/38e01c0640b31595ef4f081244b4392bd73759b9
"Subject gets number of ideas equal to overlords" extended to colonial nations and client states via decision.
Fierce Negotiatior no longer fierce when negotiating a peace deal (0 impact on peace deals up from -10)
Tech 31 and 32 now unlock further idea groups
NDefines.NMilitary.LOOT_DEVASTATION_IMPACT = 10 -- down from 20 (unexpected impact on coastal raiding devastation caused)

**Comment by Grociu** [comment] 2020-05-18 15:01
The docs are up to date as of 18.05.2020 release v2.7.2 35825004746b417a497572e34e39a1fe58db6661

**Comment by Grociu** [comment] 2020-05-22 12:05
May 25th 2020
General development curve changed via modifiers:
development_scaled = local_development_cost = 0.025 (up from 0.02)
manpower = local_development_cost = 0.005 (down from 0.01)
provincial_production_size = local_development_cost = 0.005 (down from 0.01)
provincial_tax_income = local_development_cost = 0.005 (down from 0.01)
This makes early dev cheap, late dev expensive.
Numbers readjustments on Natural Dev modifiers, original numbers too high: The higher development you have the harder is to dev up.
Significantly less likely to Natural Dev over 40 total dev.
Added installation instructions to the README.md file. Readjustments of GitHub automation.

May 24th 2020
Numbers readjustments on Natural Dev modifiers, original numbers too high.

May 23rd 2020
Rebalance of Natural Development (Dev Ideas):
You will now get the same amount of development regardless of country size.
You will now get an average of 50 monarch points worth of development (at 0% dev cost increase)
Natural Development not directly dependent on prosperity/devastation, only on it's effect on dev costs.
Added a Pacific Islands Trade Node, rework of East Asia and Pacific trade nodes
Removed redundant flags
Further map improvements to American Trade

May 21st 2020
Rum and Venetian missions now more powerful!
NDefines.NGovernment.MAMLUK_ABILITY_COST = 25 (up from 23)
NDefines.NGovernment.MAMLUK_RECRUIT_MANPOWER_MULTIPLIER = 42 (down from 45)
NDefines.NGovernment.MAMLUK_SELL_SLAVES_DUCATS_MULTIPLIER = 2.5 (down from 3)
NDefines.NGovernment.PROMOTE_MAMLUK_CULTURE_DURATION_YEARS = 4 (down from 5)
Missions will now recognize American religious reforms

May 20th 2020
New release will now also release the no-graphics branch
American Trade tweaks:  
    New trade routes:
        Mississippi River -> Mexico
        Northern Andes -> Mexico
AI now gets 50 free leaders (temporary fix as it's ignoring the limit when at war)
When you stop being a horde you no longer retain Horde Unity and you get proper ideas.
AI will use defensive edict less agressively 

May 19th 2020
All mission triggers now properly use the new mod buildings. 
Spain can be now formed by both ARA and CAS easier.
Cossacks at neutral loyalty now give cavalry combat ability.
Disable Estate disaster trigger for Trade Company Estate Disaster
Further minor tweaks to American trade map

May 18th 2020
AI will now use the Mamluk government abilities
AI on EU4_VERY_HARD now gets: 
	manpower_recovery_speed = 0.25
	global_manpower_modifier = 0.5
	land_forcelimit_modifier = 0.25
	naval_forcelimit_modifier = 0.25
	inflation_reduction = 0.05
	global_unrest = -2
	war_exhaustion = -0.05
	all_power_cost = -0.1
	interest = -1
	ae_impact = -0.2
AI on EU4_HARD now gets: 
        manpower_recovery_speed = 0.25
	global_unrest = -1
	war_exhaustion = -0.05
	interest = -1
	ae_impact = -0.2
Manpower edict now only gives manpower recovery instead of flat manpower recovery
AI logic for manpower edict tweaked
AI more likely to use trade edict in high trade provinces
NDefines.NAI.ACCEPTABLE_BALANCE_DEFAULT = 1.6  (up from 1.5)
NDefines.NAI.HOME_FLEET_MAX_RATIO = 0.4 (down from default 0.85)
NDefines.NAI.EDICT_VALUE_THRESHOLD = 100 (down from default 120)
NDefines.NAI.PEACE_TERMS_WAR_REPARATIONS_BASE_MULT = 0.5 (up from 0.1)
NDefines.NAI.PEACE_TERMS_RELEASE_ANNEXED_HRE_MULT = 3.0 (up from 2.0)
NDefines.NAI.PEACE_TERMS_HUMILIATE_VALUE_MAX = 3.0 (up from 2.0)
NDefines.NAI.PEACE_TERMS_HUMILIATE_RIVAL_BASE_MULT = 2.0 (up from 1.0)
NDefines.NAI.PEACE_TERMS_TRANSFER_VASSALS_BASE_MULT = 1 (up from 0.75)
NDefines.NAI.PEACE_TERMS_RELEASE_ANNEXED_BASE_MULT = 0.5 (down from 0.75)
NDefines.NAI.MIN_INCOME_FOR_SUBSIDIES = 75 (up from 50)
AI giving subsidies logic enhanced
AI fort building logic enhanced
AI more likely to buy manpower buildings
AI more likely to build manufactories in high production provinces
AI more likely to build infrastructure and marketplaces in high trade power provinces

**Closed as completed** 2020-11-05 03:12 UTC
Labels: documentation, ongoing
