### ISSUE TITLE
Elective Monarchy monarch skill bonuses don't apply

### ISSUE THREAD

**Issue by Grociu** [TheDivexz/excelmakesbelhappypack#50] opened 2020-05-02 11:08 UTC
Attempted to be addressed here: dd13b489b626f982cd6d38d185edefdfc4379377 e6877b9614200553e640af708ce2511cc1d26353

There are three ideas that are supposed to give you +1 skill for your elected ruler for elective monarchies.

There are 2 cases here:
CASE1: Generic Elective Monarchy: - `elective_monarchy_reform` - government reform
CASE2: Poland and PLC: - `elective_monarchy` - at start of game 

Currently this creates a triggered modifier, that's active while you have the appropriate idea and government type.

![](https://i.imgur.com/8ZHn6v0.jpg)

CASE1: Generic Elective Monarchy: - `elective_monarchy_reform` - government reform
When your ruler dies heirless, you get presented with an event to choose a new ruler from a list of candidates. `id=reform_me_events.11`. These options have a possibility of rolling a 0 skill monarch.

![](https://i.imgur.com/dxXbpCq.jpg)

When Ivan V takes the throne his skill does not update, neither is the bonus applied to the admin gain of the country. Therefore it can be assumed that the event ignores the triggered modifiers.

Interesting thing here is that this type of elected ruler here can get a natural born baby heir or one from a random event I guess. After death, the election event is a little different:

![image](https://i.imgur.com/JSB5Irm.jpg)

The options might not make sense, but this might be outside of the scope of this issue. (For example 'The Prince of course!' makes no sense here if flavor is to be considered as it generates a new son in his 20s instead of the baby). The important part is this: does the triggered modifier apply to the 'natural' heir? Spamming kill_heir and add_heir yielded no '0' skills and exactly one '1' skill, definitely above average. The bonus seems to apply.

CASE2: Poland and PLC: - `elective_monarchy` - at start of game
In this Poland game, I'm able to generate heirs from other tags, and once in a while there will be a 0 skill person. I am able to switch to that tag, promote heir (as I did here with Anhalt's proposed heir) and elect them into the kingship. His skill didn't improve either.

![](https://i.imgur.com/1RHE3rR.jpg)

The interesting part here is that Poland has a Polish heir generated when a ruler takes the throne. I think the bonus might apply to that character like it does in CASE1. I was unable to roll a '0' stat in 25 tries, with several 1s, but in general these heirs have amazing stats. The country bonus then seems to ignore the foreign heirs only (small sample size still, but reasonable assumption based on the data).

PROPOSED SOLUTION: For CASE1, an event might be created in vein of  `--Ruler-- takes the throne of --Country--` that will trigger on selecting those choices for event 11, that generate candidates. Depending on which ideas the country has, the only selectable option would increase the new rulers skills. For CASE2, a similar event might be appropriate, but the trigger seems harder to code to me.

**Comment by Grociu** [comment] 2020-05-02 16:57
```
country_event = {
	id = elective_ruler_elected
	title = elective_ruler_elected.t
	desc = elective_ruler_elected.d
	picture = GOOD_WITH_MONARCH_eventPicture
	is_triggered_only = yes
	option = {
		name = "elective_ruler_elected.o" #All hail!
		if = {
			limit = {has_idea = monarchie1}
			change_adm = 1
		}
		if = {
			limit = {has_idea = foreign_embassies_2}
			change_dip = 1
		}
		if = {
			limit = {has_idea = militarismus5}
			change_mil = 1
		}
	}
	option = {
		name = "elective_ruler_elected_cancel" #placeholder
	}
}
```

**Comment by Grociu** [comment] 2020-05-02 17:00
This is where I'm at, at the moment.
The issue is, that we can also turn this 'bug' into a feature. The bonuses seem to get applied to your dynastic heir, but not to the fake pretenders that are not your favorite son that you get from foreign powers (POL) or event.
If we change localization to always refer to your dynastic heir with the bonuses, this will make more sense in game. Out of a box but fits :)

**Comment by mellester** [comment] 2020-05-03 01:16
Makes sense to have the bonus only apply to you dynasty

**Comment by stackpoint** [comment] 2020-05-03 01:17
That does make sense, though it should clarify that in the tooltip.

**Comment by mellester** [comment] 2020-05-03 18:54
I have done some testing and decided to close this bug. Happy to report its working as intended.
I have created testing modifiers that gave huge adm bonus to rulers and heirs. and killed them offer and offer
![image](https://user-images.githubusercontent.com/609138/80922201-afe90800-8d7b-11ea-8084-8da3b6d3aeb4.png)
The second option of the event. 
![image](https://user-images.githubusercontent.com/609138/80922551-330b5d80-8d7e-11ea-9226-6b69b8ff1946.png)
And in general most lottery elections have a -1 malice to their rulers for example this one
![image](https://user-images.githubusercontent.com/609138/80922641-c9d81a00-8d7e-11ea-8803-cf9969b9f7d8.png)
This -1 malice therefore gives you the option of rolling a zero.
Seem like the third option of the event doesn't have it but you cant see what that ruler is. and your heir does get the +1 adm bonus.

On a side note it seems poland goverment heirs from other nations use the bonus from poland

**Closed as completed by mellester** 2020-05-03 18:54 UTC
Labels: bug
